version: '3.9'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
       ASPNETCORE_ENVIRONMENT: Development 
    volumes:
      - ./api:/bug_guzzler
